server:
  port: ${port:8093}

spring:
  application:
    name: eureka-consumer1

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:8091/eureka/
logging:
  level:
    root: info
    org.springframework: info
feign:
  client:
    config:
      order-eureka:
        logger-level: full
  hystrix:
    enabled: true


path:
  url: eureka/client