server:
  port: ${port:8085}

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    root: info
    org.springframework.web: trace
#    org.springframework: info
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: properties       # dataId 为 application的name 加 扩展file-extension的value
#        namespace: bc6379dd-fcee-4dae-a68a-f8341b19dbc0
        group: DEFAULT_GROUP

management:
  endpoints:
    web:
      exposure:
        include: refresh