server:
  port: ${port:8085}

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    root: info
    org.springframework.web: trace
#    org.springframework: info