server:
  port: ${port:8092}

spring:
  application:
    name: eureka-provider

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:8091/eureka/
logging:
  level:
    root: info
    org.springframework: info