server:
  port: 8086

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    root: info
    org.springframework: info