server:
  port: ${port:8093}

spring:
  application:
    name: eureka-consumer

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8091/eureka/
logging:
  level:
    root: info
    org.springframework: info